////////////////////////////////////////////
/// Documentation for ItrEx Core API
///
////////////////////////////////////////////

ifndef::included[]
ItrEx Api {project-version}
===========================
Sam Baskinger <sam.baskinger@yahoo.com>
:toc:
:toclevels: 6

endif::[]

:imagesdir: imgs

## General Calls

`[version]`::
    Returns the version of the API.

`[import <string or class>]`::
    Import functions into the root evaluation context.
    If the argument is a string, the class it points to is
    loaded. If the class is a +Package+ class, then its
    +importTo+ function is called. If the class is
    another type, then all static memebers that are
    +FunctionInterface+ types are registered as functions.

`[evalItrml <file>]`::
    Load the given file into memory, parse it as an
    +.itrml+ file and evaluate it in the current
    evaluation context. If you use this to load custom
    functions, realize that this must be evaluated under
    the root context or the function registrations will
    be discarded.

## Function

`[arg]`:: Pull one argument value off the argument list
    passed to the evaluation context. This is how a function
    should get its arguments.
    This will cause a NoSuchElementException to be thrown.
    Make sure `[hasArg]` is true before calling this.

`[args]`:: Return all arguments passed to the evalution context
    as an iterator.

`[function [...]`::
    Construct a function that can be called or used. See the `[args]`, `[arg]` and `[hasArg]`
    functions. +
+
----
[let
    [set f [function [if [hasArg] [arg] []]]]
    [[get f] hi]
]
----

`[hasArg]`:: Returns true if the evaluation context has an
    argument remaining. Function calls receive a new
    argument list.

`[register <name> <function>]`:: Register the given function under the given name. +
+
A typical usage would be +
+
----
[register f [function [toString [arg]]]]
----
+
This registers the funciton under the name `f`.
The reason to separate `register` from `function` is to allow for
constructions such as `[register f [curry...]]` and
`[register f [compose...]]`.

## Functional

`[callFlattened fn [args...]`::
    Call the function, +fn+ with the given arguments, flattened.
    That is, any argument in the +args+ list that is a list
    has its individual elements returned as arguments to +fn+.
    Any argument in the +args+ list that is an iterable
    will have its individual elements returned as arguments to
    +fn+. Other arguments are directly passed as elements
    to +fn+. +
+
This allows for +
+
----
[callFlattened fn [list a b] [list [list c d]]]
----
to be constructed which will result in an execution
equivalent to +
+
----
[fn a b [list c d]]
----
This is used, for instance, when +[map]+'ing lists into
arguments that must be mixed with other arguments to
function calls.

`[compose <function 1> <function 2>...]`::
    Compose 1 or more functions (_not_ function names) into
    a into a single function. Each function should take only
    1 argument, that returned from the following function.
    The last function may take any number of arguments.
    The +compose+ function does not take function names, but
    functions. Use +curry+ with no arguments to fetch functions by name. +
+
.Curry Example: This runs f(g("hello")).
----
[[compose [curry f] [curry g]] "hello"]
----

`[curry <function name> [args...]]`::
    Return a new function that will call the
    +function name+ with the given arguments and any
    additional arguments passed to the returned function.

`[foldLeft <function 1> <initial> [elements...]]`::
    This is aliased as +fold+.
    Fold the elements in the list of elements using
    +function 1+ with the given initial value.
    The +function 1+ function should take two arguments. The
    first is the folded value (starting with the +initial+ value)
    and the second argument is an element in the given list of elements.

`[pipeline <function or function name>]`::
    Given functions or function names, this will return a function that
    passes the result of the first function to the second function as an argument, and so on.
    The effect is that the functions for a processing pipeline.
    This is similar to `[compose]` but instead of `f(g(x))` this results in `g(f(x))`.
    Note that `[pipeline]` executes procedurally in order while `[compose]` will
    execute its functions recursively in reverse order. This typically only matters
    for scoping variables. +
+
.Pipeline Example: This runs g(f("hello")).
----
[[pipeline [curry f] [curry g]] "hello"]
----

## List

+[map <function> <iterator>]+::
    Return an iterator that maps the elements from +iterator+ to the result
    of applying +function+ to those elements. The elements from the argument
    iterator are not mapped using +function+ until they are requested
    from the returned iterator.
+[head <iterator>]+::
    Return the first element.
+[tail <iterator>]+::
    Consume the first element and return the remaining iterator.
+[last <iterator>]+::
    Evaluate every argument and return the result of the last one.
+[list a b c...]+::
    Evaluate all arguments and put the results into a list.
+[listFlatten <iterator 1> <iterator 2>...]+::
    Take a list of iterators and flatten all elements into a list.
    If a non-list item is encountered it is directly added to the list.
    This is more tolerant than the flatten function.
+[flatten <iterator 1> <iterator 2>...]+::
    Takes a list of iterators. Returns an iterator that will walk through
    elements of each of those argument iterators.
    Unlike +listFlatten+, this does not materialize the inputs into
    a list, allowing for memory savings.
+[flatten2 < <iterator1>, <iterator2> >, < <iterator3>, <iterator4> >+::
    Just +flatten+ will take iterators and concatenate them. However, when dealing with the
    output of something like a call to +[map]+ you can easily end up with a single iterator
    that contains iterators. In this case, flatten would just return that single iterator with no change.
    What we really want is a way to unwrap the outer iterator and concatenate the inner elements. +Flatten2+ does
    this. It is equivalent to a call to +[callFlatten [curry flatten]] ...]+. +
+
.Flatten2 Example: This returns the iterator [1, 2, 3, 4, 5, 6]
----
[flatten2 [list [list 1 2] [list 3, 4]] [list 5 6]]
----


## String

+[stringJoin joinString string1 string2...]+::
    Takes 1 or more strings. Returns a string joined by the first string.
    If this encounters an iterator as an argument it will drain the iterator,
    joining each of those elements as a string.
+[stringSplit splitPattern string]+::
    Split the second string using the first string as a regular expression.
+[stringConcat string1 string2]+::
    Concatenate all arguments as strings.

## Casting

+[toString arg]+::
    Return the result of calling +toString()+ on the argument.
+[toInt arg]+::
    Convert the argument to an integer.
+[toFloat arg]+::
    Convert the argument to a float.
+[toLong arg]+::
    Convert the argument to a long.
+[toDouble arg]+::
    Convert the argument to a double.

## Printing

+[help <function>]+::
    Print help text for a function, if any.
+[print ...]+::
    Collect all its arguments into a single iterator and return
    that iterator. When that iterator is called, only the is the
    value printed.
+[printErr ...]+::
    Like `print` but uses standard error.

## Logging

+[logDebug ...]+::
    Log all arguments at +DEBUG+. This is very similar to +print+.
+[logInfo ...]+::
    Log all arguments at +INFO+. This is very similar to +print+.
+[logWarn ...]+::
    Log all arguments at +WARN+. This is very similar to +print+.
+[logError ...]+::
    Log all arguments at +ERROR+. This is very similar to +print+.

## Looping / Iteration

+[for <name> <iterable> <body>]+::
    For sets +name+ to each value in +iterable+. It will then evaluate the +body+
    over and over, for each value in +iterable+. The last evaluated value of
    +body+ is returned.
    Because +for+ needs to store the +body+ unevaluated it must not be directly
    curried or composed as that proxies the argument list inside the evaluation
    engine. +
+
[caption="Example: "]
.Returns the sum of 1, 2, 3 and 4.
----
[last
   [set i 0]
   [for j [list 1 2 3 4] [set i [add [get i] [get j]]]]]
----

+[range [start] <stop> [step]]+::
    Return an iterator that will walk from the +start+ to the +stop+
    by adding the +step+ value. If 1 arguments i passed, it is treated
    as the stop value, start is assumed to be 0 and step is assumed to be 1.
    If 2 values are given they are assumed to be the start and the stop values
    and the step is assumed to be 1. +
+
This throws an exception if the range would result in an infinite loop.

## Conditional

+[caseList [case ...], [case ...] ...]+::
    The `caseList` function is built to work with `case` functions, but this is not necessary.
    Find will evaluate each of its arguments, in order, until it finds a result.
    A result is _found_ if the argument either evaluates to _true_ or is an interable object
    and its first element evaluates to _true_. In the case of an iterable element, the second
    element in the iterable is returned as the actual result. In the case of a non-iterable,
    then just true is returned.
    If nothing is found, then null (not _false_) is returned. +
+
Case Lists are slightly preferred over `[if]` constructs because the implementation of `if`
has to short-circuit the evaluating iterator in order to skip over the `then` clause without
evaluating it. This works, but is less elegant.

+[case <predicate> <success>]+::
    The case function is useful when used with the `find` function. Case takes two arguments and returns
    a list of two results. The first argument to `case` is a predicate. If this evaluates to _true_,
    then the second argument is evaluated and the list `[true, r]` is returned where `r` is the result
    of the second expression's evaluation. If the predicate evaluates to _false_ then the list
    `[false, null]` is returned.

+[if <predicate> <true branch> <false branch>]+::
    If +predicate+ is true, then the +true branch+ is evaluated
    and returned.
    If +predicate+ is false _and_ +if+ has not been curried or composed
    with another function, the +true branch+ is skipped and the +false branch+
    is evaluated and returned. If your +true branch+ has no side effects
    and is not computationally expensive, this should not make any difference.

+[and <arg1> <arg2>...]+::
    This returns the logical +and+ of the arguments. An argument is considered
    false if it is literally a +False+ object or +null+. It is true otherwise.
    If no arguments are given, this defaults to true.

+[or <arg1> <arg2>...]+::
    This returns the logical +and+ of the arguments. An argument is considered
    false if it is literally a +False+ object or +null+. It is true otherwise.
    If no arguments are given, this defaults to false.

+[not <arg>]+::
    Invert and return the logical inversion of the last argument.
    +[not a_string]+ evaluates to +false+.
    If more than 1 argument is given the inversion of the last one is returned.

+[eq <args>...]+::
    Return true if all arguments are Comparables and equal to each other.

+[lt <args>...]+::
    Return true if all arguments are Comparables and are in ascending order.

+[lte <args>...]+::
    Return true if all arguments are Comparables and are in ascending order
    or adjacent elements are equal.

+[gt <args>...]+::
    Return true if all arguments are Comparables and are in descending order.

+[gte <args>...]+::
    Return true if all arguments are Comparables and are in descending order
    or adjacent elements are equal.



## Variables

+[let ...]+::
    Create a child scope. This scope is discarded when
    the let expression finishes evaluating. Values set with +set+
    will then be discarded. The last value passed to let
    is what is returned.
+[get <name>]+::
    Return a value previously set by a call to +set+ or that the
    user has injected in the +EvaluationContext+.
+[set <name> <value>]+::
    Set the name to the given value. If there is already a value
    set, it is discarded.
+[update <name> <value>]+::
    Update the name to the given value in the context in which
    is was defined. If there is _not_ already a value
    set, this is an error and an exception is raised.

## Concurrency

[NOTE]
These function will easily crash your program. The core API is not
thread-safe. These are provided as a way to safely call _your_ thread safe
function implementations, should you choose to write your own functions.

+[thread <iterator>]+::
    This takes a single iterator as an argument and wraps it in another
    iterator which is returned. When an element is fetched from the returned
    iterator a call to +next()+ on the argument iterator is scheduled and
    a +Future+ is returned to the caller. Order from the source iterator is
    no guaranteed. Results from this function may be passed to +join+
    to block and unwrap the results.
+[join <iterator>]+::
    This takes a single iterator that returns +Future+s. The +thread+ function
    can map an iterator to an iterator of futures. +
+
----
[join [thread [my_thread_safe_iterator]]]
----

### Performance

Passing the result of +thread+ directly to +join+ will result in single threaded
performance. This is because most functions attempt to only evaluate
something if asked for it. As such, nothing is scheduled to be done by +thread+
until +join+ asks for it. Since +join+ blocks for every +Future+ it receives
we will never enjoy the parallelism available.

[caption="Example 1: "]
.Single Threaded Performance
----
[list
    [join
        [thread [get "my_threadsafe_iterator"]]]]
----

One way to improve this to materialize all the +Future+ objects returned
by the iterator from +thread+ into a list before passing that list to
+join+.

[caption="Example 2: "]
.Threaded Performance with a List
----
[list
    [join
        [list [thread [get "my_threadsafe_iterator"]]]]]
----

The downside of this approach is that we must pay the memory cost of a
list.
