SDSAI ItrEx
===========
Sam Baskinger <basking2@yahoo.com>
:toc:

:imagesdir: imgs

## The SDSAI Iterator Expressioin Language

This software is available under the MIT license. See link:https://raw.githubusercontent.com/basking2/sdsai/master/sdsai-itrex/LICENSE[+LICENSE+] for more
information.

## ItrEx - A simple evaluator

ItrEx specifies and implements an _evaluator_. That is, it doesn't particularly
care what the language is that captures the data from the human into text,
it only cares about taking a Java List object and evaluating it to a value.

ItrEx doesn't try to be a general purpose language. This is important.
The developer that chooses to use ItrEx will develop it into a language to
suit their use case, adding functions that have meaning to them.
ItrEx does provide a few basic functions, but mostly to support evaluation.

### Functions

.Info Functions
* version - Takes no arguments and returns the version of this pakcage.

.Functional Functions
* +curry+ - This takes a list of 1 or more arguments.
            The first argument should be a string
            or a `FunctionInterface` object.
            The rest of the arguments are stored in
            a list for use at dispatch time.
* +compose+ - Compose 1 or more functions
              such that `["compose, "f", "g", "x"]`
              runs `f(g(x))`.

.List Functions
* +map+ - This take a function and applies it
          to each of the following arguments.
* +head+ - Return the first element of the first argument.
           The first argument should be a list.
* +last+ - Evaluate every argument and return the
           result of the last evaulation.
* +tail+ - Consume the first element of the first
           argument and return the rest.
* +list+ - Materialize all arguments into a list
           and return that list.
* +listFlatten+ - Take a list of iterators and flatten
                  all elements into a list.
                  If a non-list item is encountered
                  it is directly added to the list.
                  This is more tolerant than
                  the flatten function.
* +flatten+ - Takes a list of iterators. Returns
              an iterator that will walk through the
              elements of each of those argument iterators.

.String Functions
* +stringJoin+ - Takes 1 or more strings. Returns
               a string joined by the first string.
* +stringSplit+ - Split the second string using the first
                string as a regular expression.
* +stringConcat+ - Concatinate all arguments as strings.

.Printing Functions
* +help+ - Print help text for a function, if any.
* +print+ - Print each argument to standard out as
            it is requested by a caller.
            If `["print", ...]` is the top level
            of an expression, nothing will be printed
            because nothing will be requested.
* +printErr+ - Like `print` but uses standard error.

.Logging Functions
* +logDebug+ - Like print, but logs at `DEBUG` level.
* +logInfo+ - Like print, but logs at `INFO` level.
* +logWarn+ - Like print, but logs at `WARN` level.
* +logError+ - Like print, but logs at `ERROR` level.

.Conditional Functions
* +if+ - Takes 3 arguments. Evaluates the second
         argument only if the first is true.
         Otherwise only the 3rd argument is evaluated.

.Variables Functions
* +let+ - Create a child scope that is discarded
        when the let expression finishes evaluation.
* +get+ - Takes a single value and returns a previously
        set value.
* +set+ - Takes two arguments. The second is stored
        using the first as a key by which it can be
        retrieved.

.Concurrency Functions
* +thread+ - Takes a single iterator as an argument
             and returns a future that processes
             the call to `next()`.
             Iterators passed to this
             must have thread-safe `next()` calls.
             It is recommended that `thread` be materialized
             into a list before passing to `join`
             to force maximum concurrency.
* +join+ - This takes a single iterator as an argument
           and waits on the futures produced by it.

## Itrml - A simple expression language

Itrml, pronounced (It-er-am-l), is a particular implementation of a
very simple S-Expression language. There is, intentionally, nothing very
interesting in it. It is meant to capture and encode data
for use by ItrEx when JSON is too verbose.

### Data Types

* Lists - Lists are any sequence of literals or lists surrounded by square
  (+[]+) braces. Elements of a list are optionally separated by commas.
  Commas may be used, or not used, interchangeably in a list. This is to
  support a very natural function calling syntax of +
+
----
[myFunction arg1, arg2, arg3]
----
+
Notice how the arguments are separated by commas, but the function
call is not followed by a comma. This is a stylistic choice.
* Literals - anything that is not a list.
** Integer valuers. These are any sequence of digits not suffixed with
   +l+ or +L+ which denote a Long value.
** Long values. These are denoted by any sequence of only integers followed by
   nothing, an +l+ or an +L+. The following are all valid Long integers. +
+
----
2341l
34L
----
+
** Double values. 
   They are denoted by a series of digits with an optional decimal point and
   more digits. A Double may be terminated with a +d+ or +D+ to distinguish
   it from a Long when there are no decimal digits. For example. +
+
----
1.0
32d
3D
4.4
----
+
The above are all double values.
** Quoted Strings - Any sequence of characters surrounded by +"+.
   Characters may be escaped such that the string value
   +abc\"123\"+ would result in the string value +abc"123"+.
** Words - Unquoted Strings. These are any token that is not quoted.
  It is taken to be a string. There are no identifiers or variables
  in this expression language, just values. Semantic meaning
  is added by ItrEx if the resultant structure is passed to it for evaluation.
