SDSAI ItrEx ${project.version}
==============================
Sam Baskinger <sam.baskinger@yahoo.com>
:toc:

:imagesdir: imgs

## The SDSAI Iterator Expression Language

This software is available under the MIT license. See link:https://raw.githubusercontent.com/basking2/sdsai/master/sdsai-itrex/LICENSE[+LICENSE+] for more
information.

## ItrEx - A simple evaluator

ItrEx specifies and implements an _evaluator_. That is, it doesn't particularly
care what the language is that captures the data from the human into text,
it only cares about taking a Java List object and evaluating it to a value.

ItrEx doesn't try to be a general purpose language. This is important.
The developer that chooses to use ItrEx will develop it into a language to
suit their use case, adding functions that have meaning to them.
ItrEx does provide a few basic functions, but mostly to support evaluation.

## IterEx API

:included: true
:leveloffset: 1

include::api.adoc[]

:leveloffset: 0
:included!:

## Itrml - A simple expression language

:included: true
:leveloffset: 1

include::language.adoc[]

:leveloffset: 0
:included!:

## ItrEx Math Evaluator

:included: true
:leveloffset: 1

include::math_evaluator.adoc[]

:leveloffset: 0
:included!:
