name: Build
on:
    push:
    #   branches:
    #   - main
    pull_request:
    workflow_dispatch:

jobs:
    build:
        runs-on: ubuntu-latest
        name: Build
        steps:
        - uses: actions/checkout@v4
        - uses: actions/setup-java@v4
          with:
            distribution: temurin
            java-version: 11
        - name: Build
          env:
            OSSRH_PASSWORD: ${{ secrets.OSSRH_PASSWORD }}
            OSSRH_USERNAME: ${{ secrets.OSSRH_USERNAME }}
            SIGNING_KEY: ${{ secrets.SIGNING_KEY }}
            SIGNING_KEY_PASSPHRASE: ${{ secrets.SIGNING_KEY_PASSPHRASE }}
          run: |
            ./gradlew clean check javadocJar asciidoctor install 

          

