name: Release
on:
  push:
    tags:
    - "*-*.*.*"
  workflow_dispatch:

env:
  TAG: ${{ github.ref_name }}

jobs:
  build:
    runs-on: ubuntu-latest
    name: Build
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 11
      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v4
        with:
          cache-disabled: false
      - name: Release
        env:
          OSSRH_PASSWORD: ${{ secrets.OSSRH_PASSWORD }}
          OSSRH_USERNAME: ${{ secrets.OSSRH_USERNAME }}
          SIGNING_KEY: ${{ secrets.SIGNING_KEY }}
          SIGNING_KEY_PASSPHRASE: ${{ secrets.SIGNING_KEY_PASSPHRASE }}
        run: |
          eval $(echo "$TAG" | sed -E 's/(.*)-([[:digit:]]+\.[[:digit:]]+\.[[:digit:]]+.*)/PROJ=\1;VERSION=\2/g')
          ./gradlew ":$PROJ:release" -Prelease.versionPropertyFile="$PROJ/gradle.properties" -Prelease.useAutomaticVersion=true -Prelease.releaseVersion="$VERSION"
      - name: Publish
        env:
          OSSRH_PASSWORD: ${{ secrets.OSSRH_PASSWORD }}
          OSSRH_USERNAME: ${{ secrets.OSSRH_USERNAME }}
          SIGNING_KEY: ${{ secrets.SIGNING_KEY }}
          SIGNING_KEY_PASSPHRASE: ${{ secrets.SIGNING_KEY_PASSPHRASE }}
        run: |
          git checkout "$TAG"
          ./gradlew publish
